<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: 2103
 * Date: Mon, 18 Jun 2018 15:42:31 +0200
 */

$conf['title'] = 'voilier brandi';
$conf['lang'] = 'fr';
$conf['sidebar'] = '';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,recent,revisions,search,register,check,subscribe,unsubscribe,source,export_raw';
$conf['remote'] = 1;
$conf['htmlok'] = 1;
$conf['mediarevisions'] = 0;

// end auto-generated content
