<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: obriand
 * Date: Fri, 19 May 2017 17:02:56 +0200
 */

$conf['title'] = 'obriand wiki';
$conf['lang'] = 'fr';
$conf['sidebar'] = '';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,recent,revisions,search,register,check,subscribe,unsubscribe,source,export_raw';
$conf['mediarevisions'] = 0;

// end auto-generated content
